name: GeospatialPython
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python=3.10
  - pip
  - cartopy
  - census
  - cryptography
  - dask
  - datashader
  - descartes
  - esda
  - fiona
  - folium
  - gdal
  - geopandas
  - geoplot
  - geopy
  - geos
  - geotiff
  - geoviews
  - h3
  - holoviews
  - inequality
  - ipykernel
  - ipyleaflet
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - libpysal
  - matplotlib-base
  - matplotlib-inline
  - mgwr
  - numba
  - numpy
  - numpydoc
  - openssl
  - pandas
  - plotly
  - pointpats
  - proj
  - pygeos
  - pykrige
  - pyproj
  - pysal
  - pyspark
  - pulp
  - rasterio
  - rasterstats
  - requests
  - requests-futures
  - scikit-learn
  - scipy
  - seaborn
  - sentinelsat
  - shapely
  - spaghetti
  - spglm
  - spint
  - splot
  - spopt
  - spreg
  - spvcm
  - statsmodels
  - tobler
  - osmnx
  - pip:
    - absl-py==1.3.0
    - cspy==1.0.2
    - gmaps==0.9.0
    - googlemaps==4.6.0
    - jellyfish==0.6.1
    - ortools==9.4.1874
    - protobuf==4.21.9
    - urllib3==1.26.12
    - us==2.0.2
    - vrpy==0.5.1
    - spatialpandas==0.4.6
    - git+https://github.com/totallypredictable/pyidw
